### ISSUE TITLE
X-ray googles cheatsheet in spanish

### ISSUE THREAD

**Issue by alvarmaciel** [mozilla/mozilla-club-activity-hack-the-news#10]
Here is the link to x-ray google in spanish an the pdf in spanish
-https://d157rqmxrxj6ey.cloudfront.net/amaciel/18570/
- https://ia601503.us.archive.org/29/items/x-rayGogglesMachete/x-rayGogglesMachete.pdf

**Comment by soapdog** [comment]
Changed the content to use your thimble make in Spanish: https://d157rqmxrxj6ey.cloudfront.net/amaciel/18570/

Do you have one for the HTML Cheatsheet?

Awesome job as usual my friend! :smile_cat:
