### ISSUE TITLE
Translation of aside.md into Dutch

### ISSUE THREAD

**Issue by gvanwaelvelde** [mozilla/mozilla-club-activity-hack-the-news#11]
#### Publiek
- 8+
- beginnende kritische denkers
#### Materialen
- Pen en papier
- Webbrowser
- (optioneel) [afgedrukt HTML spiekbriefje](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17418/)
- (optioneel) [afgedrukte X-Ray Goggles hulpgids](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17419/)
#### Leerdoelstellingen
- Leer het verschil tussen originele inhoud en een remix
- Gebruik X-Ray Goggles om een webpagina te veranderen en een bepaald thema te geven
- Beoordeel een remix van een andere leerling
#### Activiteit in Actie!

![Image](http://mozilla.github.io/webmaker-curriculum/images/hackthenews-action.jpg)
[Hive Pittsburgh: Pittsburgh Project Youth begint met hacken](http://hivepgh.sproutfund.org/blog/2014/12/15/pittsburgh-project-youth-get-hacking/)
#### Remixes van de gemeenschap

Kijk hoe anderen deze activiteit aangepast hebben aan hun eigen doelpubliek in ons [Discussie Forum](https://discourse.webmaker.org/c/curriculum).

**Comment by soapdog** [comment]
Thanks a lot for the awesome work! Its live at http://mozilla.github.io/mozilla-club-activity-hack-the-news/#nl
