### ISSUE TITLE
Translation of activity.md into Dutch

### ISSUE THREAD

**Issue by gvanwaelvelde** [mozilla/mozilla-club-activity-hack-the-news#12]
---

title: Het nieuws hacken
github: mozilla/mozilla-club-activity-hack-the-news
image: hackthenews.png
competencies:
### Het nieuws hacken

Gemaakt door [Hive New York City](http://hivenyc.org/) en geremixt voor Clubs door [Mozilla](https://webmaker.org/mentor).

Leerlingen zullen X-Ray Goggles gebruiken om een nieuwswebsite te remixen, zo leren ze over **open-gelicenseerde hulpbronnen, verschillende soorten media, en hoe ze iets nieuws op het Web kunnen maken met een remix.**

45 minuten tot één uur
### Voorbereiding

**Vul de** [voorbereidingsvragenlijst](http://goo.gl/forms/Uua6yKIy5E) **in**.

Doe vervolgens **de activiteit zelf** om ze te leren kennen. U kunt misschien een Webmaker-account aanmaken en delen met uw leerlingen. Dit zal later tijd besparen wanneer uw leerlingen klaar zijn om hun remixes te publiceren.

[Bekijk deze definitie van de term "Hacken"](https://wiki.mozilla.org/Webmaker/Teach/Terminology#Hack), zo kunnen uw leerlingen (en collega's!) het woord in een positieve context leren kennen.

Optioneel: Druk het [HTML spiekbriefje](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17418/) en de [X-Ray Goggles hulpgids](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17419/) af.

---

10<br>min
### Inleiding

Verwelkom uw leerlingen en leg uit dat we in deze activiteit het concept "remixen" gaan verkennen. Geef iedereen pen en papier.

> Verdeel uw leerlingen in groepjes van twee en vraag hen om hun favoriete fictieve personage te tekenen. Het moet niet heel duidelijk of gedetailleerd zijn — gewoon een snelle tekening.

Laat na een paar minuten de leerlingen hun tekeningen uitwisselen. Vraag de leerlingen om iets aan de tekening van hun partner toe te voegen. Leg uit dat ze nu aan het remixen zijn!

---

25<br>min
### Het nieuws hacken met X-Ray Goggles

Laat de leerlingen in groepjes van twee een webbrowser openen. Als er niet voldoende computers zijn, doe het dan voor op één computer en laat de groepjes dan om beurten het zelf proberen.
#### Installeer X-Ray Goggles

Ga naar [goggles.webmaker.org](https://goggles.webmaker.org/). Demonstreer hoe je de grote gele “X-Ray Goggles activeren” knop naar je browser's Bladwijzerwerkbalk kan slepen.

![Image](http://mozilla.github.io/webmaker-curriculum/images/newshack-example-animated.gif)
#### Ga naar een nieuwswebsite

Vraag suggesties voor een goede nieuwswebsite. Denk aan lokale kranten, uw schoolkrant, of nationale nieuwssites. Probeer een website te vinden die veel HTML gebruikt en niet teveel JavaScript, dat zal het makkelijker maken on dingen te remixen.

> Geen paniek — u bent de website niet aan het hacken voor anderen. U verandert alleen een lokale versie van de site, die u alleen kan zien.
#### Kies een thema om te remixen

Geïnspireerd door de personages van de Inleiding, kiest u een remix thema. Bijvoorbeeld, Nyan Cat, de Kraken, King Kong, of andere personages. 

![Image](http://mozilla.github.io/webmaker-curriculum/images/newshack-example.png)
#### Activateer de Goggles

Klik op de Goggles in uw Bladwijzerwerkbalk om ze in te schakelen. Wanneer u nu uw muis beweegt over een deel van de pagina, kunt u automatisch de onderliggende code bekijken.
#### Klik op de “remix” knop

Druk op “R” op het toetsenbord om een element te remixen.
#### Verander de tekst en gebruik nieuwe afbeeldingen

Probeer de titel van het artikel te veranderen of herschrijf het artikel zodat het over het gekozen fictieve personage gaat. Bewerk enkele van de links en speel wat met de grootte en de kleur van hetlettertype.

Beweeg met de muis over een afbeelding en klik “R” / “Remix.” Plak dan het adres/URL van uw nieuwe afbeelding. Om een afbeelding van Facebook of Instagram te plukken, klikt op het afbeelding, en dan klikt u met de rechtermuisknop en "Afbeeldingslocatie kopiëren".

> **TIP:** Hoe een open-gelicenseerde afbeelding vinden?. De Creative Commons zoekpagina of de geavanceerde instellingen in Google helpen u om gemakkelijk een afbeelding te vinden met de toestemming om ze te gebruiken. Klik met de rechtermuisknop of control-klik op de afbeelding die u wilt en kies: “Afbeeldingslocatie kopiëren.” (Or “Afbeeldings-URL kopiëren” or “Afbeeldingsadres kopiëren”, afhankelijk van uw webbrowser.) Kopiëer dan de nieuwe afbeeldings-URL in de plaats van de oude. Let op dat u de aanhalingstekens behoudt!

![Image](http://mozilla.github.io/webmaker-curriculum/images/newshack-example-2.png)
#### Delen

**Uw remix publiceren.** Wanneer u klaar bent, klik dan op de Publiceren knop, of druk op P op uw toetsenbord. Dit maakt uw wijzigingen zichtbaar voor anderen op het web.

**Ga een stap verder.** Laat leerlingen hun hacks delen met de nieuwssites die ze geremixt hebben. De meeste nieuwssites zitten op Twitter, dus probeer om een link naar hen te tweeten en kijk hoe ze reageren.

---

10<br>min
### Beoordelen

Toon een paar geremixte pagina's en vraag leerlingen om te vertellen wat ze veranderd hebben. Stel vragen zoals:

> Welke versie van de website vind je het leukst? Wat zou je nog willen remixen? Wat wilde je remixen, maar lukte niet? Waarom niet? Hoe kan je nog media vinden die je kan remixen?

Als er voldoende tijd is, **nodig leerlingen uit om hun partner's nieuwe pagina's te blijven remixen.** U kan bespreken hoe het Web het gemakkelijk maakt om inhoud op deze manier te wijzigen en dat we altijd remixen en verderbouwen op datgene wat anderen gemaakt hebben.

U kan het ook hebben over betrouwbaarheid en geloofwaardigheid en hoe remixes laten zien dat je moet nadenken over hoe je informatie leest en interpreteert en wie ze gepubliceerd heeft. Dit kan verder bouwen op de [vorige Kraken activiteit](http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#nl).

**Comment by soapdog** [comment]
Thanks a lot for the awesome work! Its live at http://mozilla.github.io/mozilla-club-activity-hack-the-news/#nl
