### ISSUE TITLE
Localization of activity.md into Chinese Simplified

### ISSUE THREAD

**Issue by nizibaba** [mozilla/mozilla-club-activity-hack-the-news#16]
---

title: Hack the News
github: mozilla/mozilla-club-activity-hack-the-news
image: hackthenews.png
competencies:
### 骇客新闻

Made by [Hive New York City](http://hivenyc.org/) and remixed for Clubs by [Mozilla](https://webmaker.org/mentor).

活动人员通过使用**X-Ray Goggles了解网页的构成，了解什么是公开授权的资源，不同形式的媒体，以及如何通过用X-Ray Goggles在网络上创造新的作品。

45分钟--一个小时
### 活动前期准备

_完成_\* [活动前期调查表](http://goo.gl/forms/Uua6yKIy5E).

接下来充分准备你自己的活动来熟悉它。你不妨设置与你的学生共享Webmaker帐户。当他们准备发布自己的作品，这以后将节省学生注册的时间。

[请活动的参与者查看一下 "Hack"这个单词的意义，](https://wiki.mozilla.org/Webmaker/Teach/Terminology#Hack), 这样就可以帮助你的学生（和你的同事！）理解对这个词的积极方面。

可选: 打印 [HTML cheatsheet（简介）](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17418/) 和 [X-Ray Goggles 使用指南](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17419/).

---

10<br>分钟
### 活动介绍

欢迎您的学生并解释说，本次活动我们将探索“Remixing（再创作）”。 给每个学生一张纸和一支铅笔。
主持人介绍本地社区，告诉活动参与者 我们将一起去了解一下网页背后的秘密，并尝试体验去做一个**神通广大的黑客**！！！

> 在这一时间段，让学生画出自己喜欢的虚构人物无需准确性或太多细节-只需绘制迅速。

几分钟后，要求交换他们的图纸。 提示学生添加自己喜欢的东西到他们的合作伙伴的绘图中去。 解释说，这是“Remixing（再创作）”在行动！

---

25<br>分
### 使用-Ray Goggles去“攻克” 纽约时报

在这一部份，我们会要求学生打开Firefox浏览器，安装 X-Ray Goggles
#### 安装 X-Ray Goggles

要求同学在地址栏输入https://goggles.webmaker.org/，进入 [ X-Ray Goggles安装界面](https://goggles.webmaker.org/).  演示如何拖动黄色的大“ X-Ray Goggles”按钮，浏览器的书签工具栏。

![Image](http://mozilla.github.io/webmaker-curriculum/images/newshack-example-animated.gif)
### 让学生随意选择一家网站，当地最有影响的网站，报纸（友情提示： 尽量去找大量使用HTML的网站，而不是大量运用JavaScript的网站，因为它会更容易为你的学习者提供更好的感受。

> **别担心 -你并没有违反任何法律，也不会侵犯任何人的权利，你看的，和你即将修改的仅仅是一个快速产生的本地副本。**
#### 确定一个主题或者说想一想等一会你该如何修改一个网站

我们会在这个时候给学生播放我们是如何恶搞一个本地新闻的视频，你会听到底下一片片的惊呼声

![Image](http://mozilla.github.io/webmaker-curriculum/images/newshack-example.png)
#### 开始行动

打开一个你将要大展身手的网站，点击Firefox浏览器工具栏上的X-Ray Goggles标识，如果你的网速够快，很快就会发现当前屏幕发生了变化，你的鼠标指向当前屏幕的不同位置，他会发生不同的变化，显示不同的颜色
#### 点击 “remix” 按钮

按下键盘上的“R”重新组合任何元素。
#### 尝试修改一下网页中的图片和文本

请尝试更改标题或重写一些根据您的虚构人物的故事。 编辑某些环节和字体大小和颜色玩。

将鼠标悬停在页面上的图像，并按下“R”，接下来，去网上找一张你喜欢的任意图片，右键复制图片地址，再回来替换原来的图片地址就可以啦

> **技巧提示:你会发现，Firefox是如此好用，很轻易的就可以得到图片的原始网址** ：如何找到和开放授权图像交换 知识共享搜索页面或高级设置在谷歌的帮助你轻松地找到你使用它的权限喜欢的图像。 用鼠标右键单击，或您想在图片上右击并选择：“ 复制图片位置 ”（或“复制图片网址”或“复制图片地址”，这取决于你的网络浏览器。）然后你的新图片的网址贴在上面了，不要失去了引号！

![Image](http://mozilla.github.io/webmaker-curriculum/images/newshack-example-2.png)
#### 分享，让所有人都看到你的创意

**发布您的作品。 一旦您完成后，点击发布键盘上的按钮，或按P键。 这使得您的更改在网上显示让更多的人看到。

**尝试一下这个建议**尽可能的吧你再创作的作品分享到各个社交网站，facebook ，twitter,看看大家的反应

10<br>分钟
### 反思和总结

演示几个作品页，并要求学生分享他们改变什么。 考虑提示如下：

> 你更喜欢什么版本的网站?你会什么进行修改?你希望你能重新修改，但不能是什么?为什么不呢？你怎么能找到你可以在创作的媒体?

如果时间允许，邀请学生继续通过重新混合他们的合作伙伴的新页面。您可以讨论Web怎么可以很容易地修改这样的内容，而且我们一直remix别人取得的成就。

通过这个活动，你也可以讨论网站可信度和如何理解再创作之后的变化 ？以及如何你保护你的创意，想想谁创作它。谁拥有他，这可以依靠 ，欢迎参考[深海怪兽]这个活动继续发挥(http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#en).

**Comment by soapdog** [comment]
Yay for another great Chinese L10N! Thanks a lot for your hard work! It is now live at:

http://mozilla.github.io/mozilla-club-activity-hack-the-news/#zh-s

:smile_cat:
