### ISSUE TITLE
Localization of aside.md into Chinese Simplified

### ISSUE THREAD

**Issue by nizibaba** [mozilla/mozilla-club-activity-hack-the-news#17]
#### 活动受众
- 8+
- 可以独立思考的受众
#### 活动所需材料
- 纸和笔
- 最新的Firefox浏览器
- (打印) [ HTML小抄](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17418/)
- (可选) [打印 X-Ray Goggles 使用指南](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17419/)
#### 学习目标
- 区分原创和再创作
- 使用 X-Ray Goggles 去修改一个网页，并赋予他新的主题
- 评价其他同学的作品
#### 进行中的活动!

![Image](http://mozilla.github.io/webmaker-curriculum/images/hackthenews-action.jpg)
[Hive Pittsburgh: Pittsburgh Project Youth Get Hacking](http://hivepgh.sproutfund.org/blog/2014/12/15/pittsburgh-project-youth-get-hacking/)
#### 了解不同社区再创作

Mozilla来自世界各地的志愿者和教育工作者根据这个题材进行了不同的再创作，您可以加入我们的讨论并和帮助我们进行更多的创作 [欢迎加入](https://discourse.webmaker.org/c/curriculum).

**Comment by soapdog** [comment]
Yay for another great Chinese L10N! Thanks a lot for your hard work! It is now live at:

http://mozilla.github.io/mozilla-club-activity-hack-the-news/#zh-s

:smile_cat:
