### ISSUE TITLE
Localization of activity.md into Swedish

### ISSUE THREAD

**Issue by bittin** [mozilla/mozilla-club-activity-hack-the-news#18]
---

title: Hack the News
github: mozilla/mozilla-club-activity-hack-the-news
image: hackthenews.png
competencies:
### Hacka nyheterna

Skapad av [Hive New York City](http://hivenyc.org/) och remixad för Clubs av [Mozilla](https://webmaker.org/mentor).

Eleverna kommer använda X-Ray Goggles för att remixa en nyhets hemsida, och lära sig om **öppet-licensierade resurser, olika former av media, och hur man skapar något nytt på webben genom att remixa.**

45 minuter till en timme
### Förberelser

**Genomför den** [förberedande enkäten](http://goo.gl/forms/Uua6yKIy5E).

Sen **gör aktiviteten själv för att** bekanta dig med den. You may wish sätta upp ett Webmaker konto som du kan dela med dina studenter. Detta kommer spara tid senare när dom är redo att publicera deras remixar.

[Recension om denna definition av ordet "Hack"](https://wiki.mozilla.org/Webmaker/Teach/Terminology#Hack), läs detta så att du kan hjälpa dina studenter (och kollegor!) förstå en positiv användning av ordet.

Frivilligt: Skriv ut [HTML fusklapp](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17418/) och [X-Ray Glasögons referens guide](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17419/).

---

10<br>min
### Introduktion

Välkommna dina studenter och förklara att i denna aktiviteten så kommer vi att utforska "remix." Ge varje student en bit papper och en penna.

> I par, fråga och be studenterna att skissa deras favorit fiktiva karaktär. Inget behov av äkthet eller alltför mycket detaljer - bara skissa ihop något snabbt.

Efter några minuter, får paren byta sina skisser. Be studenterna att lägga till något till sin partner skiss. Förklara att detta är remix i aktion!

---

25<br>min
### Hacka nyheterna genom att använda X-Ray Glasögonen

I samma par, om tillräckligt med utrustning finns att tillgå, be studenterna att öppna en modern webbläsare. Annars, demonstrera på en dator och forma små grupper efteråt så att studenterna kan prova själva.
#### Installera the X-Ray Glasögonen

Gå till [goggles.webmaker.org](https://goggles.webmaker.org/). Demonstrera hur man drar den stora gula “Activate X-Ray Goggles” knappen till din webbläsares bokmärkes verktygsfält.

![Image](http://mozilla.github.io/webmaker-curriculum/images/newshack-example-animated.gif)
#### Navigera till en nyhets hemsida

Fråga för förlsag på en nyhets sida. Tänk på lokala tidningar, din skolas tidning, eller en nationell nyhets sida som till exempel The New York Times eller The Guardian. Försök att hitta hemsidor som använder mycket HTML, och inte en massor Javascript så att det blir lättare för dina studenter att remixa.

> Oroa dig inte - du hackar faktiskt inte hemsidan för andra. Du ändrar en lokal version av sidan som bara du kan se.
#### Besluta dig om ett remix tema

Inspirerad av karaktärerna från introduktionen, besluta dig om ett remix tema att använda. Idéer inkluderar Nyan Cat, Kraken, King Kong, eller liknande lokalt relevanta karaktärer.

![Image](http://mozilla.github.io/webmaker-curriculum/images/newshack-example.png)
#### Aktivera Glasögonen

Klicka på Glasögonen i din bokmärkes verktygsfält för att slå på dom. Nu när du för datormusen över delar av nyhetssida, ser du koden nedanför.
#### Tryck på “remix” knappen

Tryck på “R” knappen på tangentbordet för att remixa något av elementen.
#### Ändra på texten och byta ut några av bilderna till nya

Försök att ändra rubrikerna eller skriva några av de berättelser som är baserade på din fiktiva karaktär. Redigera några av länkarna och spela med teckenstorlek och färg.

För datormusen över en bild på sidan och tryck på “R” / “Remix.” Sedan klistra in adressen / URL för den nya bilden. To grab an bild från Facebook eller Instagram, du måste högerklicka på posten, högerklicka och välj "Kopiera bildadress".

> **TIPS:** Hur man hittar och byter ut en öppet licensierade bild. Använd Creative Commons söksidan eller avancerade inställningar i Google som kan hjälpa dig att enkelt hitta en bild som du vill använda och har tillåtelse att använda. Högerklicka eller kontrollklicka på bilden du vill ha och välj "."Kopiera bilden i" (eller "Kopiera bildadress" eller "Kopiera bildadress", beroende på din webbläsare.) Sedan klistrar du in den nya bildadress över toppen istället för det gamla. Var noga med att inte förlora citattecken!

![Image](http://mozilla.github.io/webmaker-curriculum/images/newshack-example-2.png)
#### Dela

**Publicera din remix.** när du är klar, klicka på Publicera knappen, eller tryck "P" på ditt tangentbord. Detta gör dina ändringar synliga på webben för andra att se.
## **Ta det ett steg längre.** Be studenterna dela deras hacks med nyhetsstationen där deras remixer används. De flesta nyheter stationer brukar också finns på twitter, så försök twittra en länk till dem och tänk på deras reaktioner.

10<br>min
### Reflektera och granska

Demonstrera några få av dom remixade sidorna och fråga studenterna att dela vad dom har ändrat. Överväg frågor såsom:

> Vilken version av hemsidan gillade du mer? Vad mer skulle du remixa? Vad önskar du att du kunde remixa men kunde inte? Varför inte? Hur annars kan du hitta material som du kan remixa?

Om tiden tillåter, **bjud in studenterna att fortsätta genom att remixa deras kompisars nya sidor.** Du kan diskutera hur webben gör det enkelt att modifera innehåll på detta sätt och att vi alltid kan remixa och bygga på vad andra har gjort.

Du kan också diskutera trovärdighet och hur förståelse för remixar förändrar hur du läser eller tolkar information, samt börjar tänka på vem som skrivit vad. Detta kan bygga på den [tidigare Kraken aktiviteten](http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#sv).

**Comment by soapdog** [comment]
Thanks a lot for the hard work! This Swedish L10N rocks! 

http://mozilla.github.io/mozilla-club-activity-hack-the-news/#sv

:smile_cat:
