### ISSUE TITLE
Localization of aside.md into Swedish

### ISSUE THREAD

**Issue by bittin** [mozilla/mozilla-club-activity-hack-the-news#19]
#### Målgrupp
- 8+
- nybörjande kritiska tänkare
#### Material
- Papper och pennor
- Webbläsare
- (valfritt) [utskriven HTML fusklapp](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17418/)
- (valfritt) [utskriven X-Ray Glasögons referens guide](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17419/)
#### Lärandemål
- Skilja på det ursprungliga innehållet och en remix
- Använda X-Ray Glasögon för att ändra på en hemsida för att ge den ett specifikt tema
- Kritisera en annan elevs remix
#### Aktiviteten i Action!

![Image](http://mozilla.github.io/webmaker-curriculum/images/hackthenews-action.jpg)
[Hive Pittsburgh: Pittsburgh Project Youth Get Hacking](http://hivepgh.sproutfund.org/blog/2014/12/15/pittsburgh-project-youth-get-hacking/)
#### See remixar från communityt

Se hur utbildare och aktivister har anpassat aktiviteten för sina specifika målgrupper i vårt. [Diskussionsforum](https://discourse.webmaker.org/c/curriculum).

**Comment by soapdog** [comment]
Thanks a lot for the hard work! This Swedish L10N rocks! 

http://mozilla.github.io/mozilla-club-activity-hack-the-news/#sv

:smile_cat:
