### ISSUE TITLE
Translation of activity.md into Bengali(bn-BD)

### ISSUE THREAD

**Issue by khalid32** [mozilla/mozilla-club-activity-hack-the-news#2]
---

title: Hack the News
github: mozilla/mozilla-club-activity-hack-the-news
image: hackthenews.png
competencies:
### নিউজ হ্যাক করা

তৈরিকৃত [হাইভ নিউ ইয়র্ক সিটি](http://hivenyc.org/) এবং ক্লাবের জন্য রিমিক্সকৃত [মজিলা](https://webmaker.org/mentor)।

শিক্ষার্থীরা এক্স-রে গোগলস ব্যবহার করে একটি সংবাদ সংক্রান্ত ওয়েবসাইটকে রিমিক্স করবে, **প্রকাশ্যভাবে লাইসেন্সপ্রাপ্ত সম্পদসমূহ, বিভিন্ন ধরনের মিডিয়া, এবং কিভাবে রিমিক্সের মাধ্যমে ওয়েব থেকে নতুন কিছু তৈরি করা যায়** সে সম্পর্কে জানবে।

৪৫ মিনিট থেকে ১ ঘন্টা
### প্রস্তুতিকরণ

**সম্পূর্ণ করুন** [প্রাক-কার্যকলাপ প্রশ্নোত্তর](http://goo.gl/forms/Uua6yKIy5E)।

এরপর **আপনি নিজে থেকে কার্যকলাপ করুন** এর সাথে পরিচিত হওয়ার জন্য।. আপনি চাইলে একটি ওয়েবমেকার অ্যাকাউন্ট সেট-আপ করতে পারেন যেন আপনি আপনার শিক্ষার্থীদের কাছে শেয়ার করতে পারেন। এটি পরে সময় বাঁচাবে যখন তারা তাদের রিমিক্স প্রকাশের জন্য তৈরি 

থাকবে।

["হ্যাক" শব্দটির সংজ্ঞা পর্যালোচনা করুন](https://wiki.mozilla.org/Webmaker/Teach/Terminology#Hack), যেন আপনি আপনার শিক্ষার্থীদের (এবং সহকর্মীদের!) সাহায্য করতে পারেন এই শব্দের নীতিবাচক প্রসঙ্গ বুঝানোর জন্য।

ঐচ্ছিক: প্রিন্ট করুন [HTML চিটশিট](https://mozteach.makes.org/thimble/html-cheatsheet) এবং [এক্স-রে গোগলস-এর বরাতকৃত গাইড](https://mozteach.makes.org/thimble/xray-goggles-cheatsheet)।

---

১০<br>মিনিট
### সূচনা

আপনার চাত্র-ছাত্রীদের আমন্ত্রণ জানান এবং বুঝান যে এই কার্যকলাপে আমরা "রিমিক্স" অনুসন্ধান করব। প্রত্যেক ছাত্র-ছাত্রীদেরকে একটি কাগজ ও কলম দিন।

> যুগলে অবস্থায়, ছাত্র-ছাত্রীদের বলুন তাদের পছন্দের কাল্পনিক চরিত্রদের ছবি আঁকতে। নির্ভুলতা বা এতো খুঁটিনাটীর প্রয়োজন নেই - তাড়াতাড়ি আঁকলেই হবে।

কিছু সময় পর, যুগল তাদের আঁকাগুলোকে বদলাবদলি করতে দিন। ছাত্র-ছাত্রীদেরকে তার পার্টনারের আঁকাতে কিছু যুক্ত করার জন্য উদ্বুদ্ধ করুন।  তাদেরকে বুঝান যে এটি কর্মের মধ্যে রিমিক্স!

---

২৫<br>মিনিট
### এক্স-রে গোগলস দ্বারা সংবাদ হ্যাক করুন

একই যুগল দ্বারা, যদি যথেষ্ট পরিমাণ সরজ্ঞাম উপস্থিত থাকে, তাহলে ছাত্র-ছাত্রীদেরকে একটি আধুনিক ওয়েব ব্রাউজার চালু করতে বলুন।  অন্যথায়, একটি কম্পিউটারে প্রদর্শন করুন এবং পরে ছোট গ্রুপ গঠন করুন যেন ছাত্র-ছাত্রীরা নিজেরা চেষ্টা করতে পারে।
#### এক্স-রে গোগলস ইন্সটল করুন

[goggles.webmaker.org](https://goggles.webmaker.org/) এ যান। কিভাবে বড় হলুদ রঙের "Activate X-Ray Goggles" বাটনটি আপনার ব্রাউজারের বুকমার্ক টুলবারে আনা যায় তা প্রদর্শন করুন।

![ছবি}(http://mozilla.github.io/webmaker-curriculum/images/newshack-example-animated.gif)]
#### নিউজ ওয়েবসাইট নেভিগেট করুন

সংবাদ সংক্রান্ত সাইটে পরামর্শের জন্য জিজ্ঞাস করুন। স্থানীয় সংবাদপত্র, আপনার স্কুল পেপার, অথবা জাতীয় সংবাদ সংক্রান্ত সাইট যেমন দ্য নিউ ইয়র্ক টাইমস অথবা দ্য গার্ডিয়ান সম্পর্কে চিন্তা করুন। এমন ওয়েবসাইট খোঁজার চেষ্টা করুন যেখানে ভাল পরিমাণে HTML, এবং কম 

পরিমাণে জাভাস্ক্রিপ্ট ব্যবহৃত হয়েছে যেন আপনার শিক্ষার্থীরা সহজেই রিমিক্স করতে পারে।

> চিন্তা নেই — আপনি আসলে কারও জন্য সাইট হ্যাক করছেন না। আপনি সাইটের স্থানীয় সংস্করণটি বদলাচ্ছেন যা শুধু আপনি দেখতে পাবেন।
#### রিমিক্স থিম-এ সিদ্ধান্ত নিন

সূচনার চরিত্র হতে অনুপ্রাণিত হয়ে, রিমিক্স থিম-এ সিদ্ধান্ত নিন। নাইয়ান ক্যাট, দ্য ক্রাক্যান, কিংকং, অথবা একরকম স্থানীয় প্রাসঙ্গিক চরিত্রসমূহ-এর ধারনা অন্তর্ভুক্ত করুন।

![ছবি](http://mozilla.github.io/webmaker-curriculum/images/newshack-example.png)
#### গোগলস সক্রিয় করুন

সক্রিয় করার জন্য আপনার বুকমার্ক টুলবারে গোগলস ক্লিক করুন। এখন যখন সংবাদ সংক্রান্ত পেইজের উপাদানের উপর মাউস নিবেন, আপনি এর তলে কোড দেখতে পাবেন।
#### "রিমিক্স" বাটনে হিট করুন

কিবোর্ডের "R" এ হিট করুন যেকোনো উপাদান রিমিক্স করার জন্য।
#### টেক্সটটি বদলান এবং নতুন ছবি দ্বারা বদলাবদলি করুন

শিরোনামগুলো বদলানোর চেষ্টা করুন অথবা আপনার কাল্পনিক চরিত্রের উপর ভিত্তি করে কিছু গল্প পুনর্লিখন করুন। কিছু লিংকগুলো সম্পাদন করুন এবং ফন্টের আকার ও রঙ নিয়ে খেলা করুন।

পেইজের ছবির উপর মাউস নিন এবং "R"/ "রিমিক্স" হিট করুন।  এরপর আপনার নতুন ছবি এডরেস/URL-এ পেস্ট করুন। ফেসবুক অথবা ইস্টেগ্রাম থেকে ছবি নেয়ার জন্য, আপনাকে পোষ্টে ক্লিক করতে হবে, তারপর রাইট-ক্লিক ও "Copy the Image Location"-এ ক্লিক 

করতে হবে।

> **TIP:** কিভাবে প্রকাশ্যভাবে লাইসেন্সপ্রাপ্ত ছবি খুঁজবেন এবং বদলাবদলি করবেন। দ্য ক্রিয়েটিভ কমোনস সার্চ পেইজ অথবা গুগল সার্চের এডভ্যান্স সেটিংসে আপনি সহজে ব্যবহারে অনুমতিপ্রাপ্ত আপনার পছন্দের ছবির খোঁজ পাবেন। ছবিতে রাইট-ক্লিক অথবা কনট্রল-ক্লিক 

করুন এবং বাছাই করুন:  “Copy image location”। (অথবা “Copy image URL” অথবা “Copy image address”, আপনার ওয়েব ব্রাউজারের উপর নির্ভর করে।) এরপর পুরানোটির উপরে নতুন ছবির URL পেস্ট করুন। উদ্ধৃতি চিহ্ন ব্যবহার করতে ভুলবেন 

না যেন!

![ছবি](http://mozilla.github.io/webmaker-curriculum/images/newshack-example-2.png)
#### শেয়ার

**আপনার রিমিক্স প্রকাশ করুন।** যখন আপনার হয়ে যাবে, পাবলিশ বাটনে ক্লিক করুন, অথবা কিবোর্ডে P চাপুন। এটি আপনার বদলানোটি ওয়েবে দৃশ্যমান হবে যেন অন্যরা দেখতে পায়।

**আরও একধাপ নিন।** শিক্ষার্থীদের নিউজ স্টেশনে তাদের রিমিক্সগুলো দ্বারা ব্যবহৃত হ্যাকগুলো শেয়ার করতে দিন। অধিকাংশ নিউজ স্টেশন টুইটারে আছে, সুতরাং সেখানে টুইট করার চেষ্টা করুন এবং তাদের প্রতিক্রিয়া সম্পর্কে চিন্তা করুন।

---

১০<br>মিনিট
### প্রতিফলন এবং পুননিরীক্ষণ করুন

কিছু রিমিক্স করা পেইজের নমুনা প্রদর্শন করুন এবং ছাত্র-ছাত্রীরা কি কি বদলিয়েছে তা শেয়ার করতে বলুন। সতর্কগুলো বিবেচনা করুন যেমন:

> ওয়েবসাইটের কোন সংস্করণটি আপনার অনেক ভাল লেগেছে? আপনি আরও কি রিমিক্স করবেন? আপনি কোনটি রিমিক্স করতে চান যেটা করতে পারবেন না? কেন নয়? আপনি মিডিয়ায় কি কি খুঁজবেন যা আপনি রিমিক্স করবেন?

যদি যথেষ্ট সময় থাকে, **ছাত্র-ছাত্রীদের আমন্ত্রণ জানান তাদের পার্টনারের নতুন পেইজ রিমিক্স চালু করার জন্য।** এই উপায়ে বিষয়বস্তু বদলিয়ে কিভাবে ওয়েবকে সহজ করা যায় এবং অন্যরা যা বানিয়েছে তার উপর সবসময় রিমিক্স ও গঠন করতে পারবে তা নিয়ে আলোচনা করতে পারেন।

বিশ্বাসযোগ্যতা এবং কিভাবে সমবেদনাশীল রিমিক্স আপনার পড়ার ধরন অথবা তথ্য অনুবাদকরণ কিভাবে বদলাবে সে বিষয়ে আলোচনা করতে পারেন, সেইসাথে কে ইহার লেখক সে সম্পর্কে চিন্তা করতে পারেন। এটি নির্মাণ করতে পারেন [পূর্ববর্তী ক্রাক্যান কার্যকলাপ 

দিয়ে](http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-kraken.html)।

**Comment by soapdog** [comment]
Thanks a lot for the translation!!! :smile_cat: this is now live. This is awesome work!
