### ISSUE TITLE
Correction localization of aside.md to Bengali (bd)

### ISSUE THREAD

**Issue by mijanurrahman** [mozilla/mozilla-club-activity-hack-the-news#4]
#### শ্রোতৃমণ্ডলী
- ৮+
- শুরুর সংকটপূর্ণ চিন্তাবিদ
#### উপকরনসমূহ
- কাগজ ও কলম
- ওয়েব ব্রাউজার
- (ঐচ্ছিক) [প্রিন্ট করা HTML চিটশিট](https://mozteach.makes.org/thimble/html-cheatsheet)
- (ঐচ্ছিক) [প্রিন্ট করা এক্স-রে গোগলস-এর বরাতকৃত গাইড](https://mozteach.makes.org/thimble/xray-goggles-cheatsheet)
#### শেখার উদ্দেশ্য
- মূল বিষয়বস্তু এবং একটি রিমিক্স চিহ্নিত করা
- এক্স-রে গোগলস ব্যবহার করে একটি ওয়েব পেইজকে পরিবর্তন করে একটি বিশেষ থিম দেয়া
- আরেক শিক্ষার্থীর রিমিক্স সমালোচনা করা
#### কার্যকলাপের পদক্ষেপ!

![ছবি}(http://mozilla.github.io/webmaker-curriculum/images/hackthenews-action.jpg)]
[হাইভ পিচবার্গ: পিচবার্গ প্রজেক্টে তরুনরা হ্যাক করে](http://hivepgh.sproutfund.org/blog/2014/12/15/pittsburgh-project-youth-get-hacking/)
#### কমিউনিটির রিমিক্সসমূহ দেখুন

দেখুন কিভাবে শিক্ষাবিদ ও কর্মীরা এই কার্যকলাপকে কোন নির্দিষ্ট দর্শকের জন্য রিমিক্স করেছে [আলোচনা ফোরামে](https://discourse.webmaker.org/c/curriculum)।

**Comment by soapdog** [comment]
Corrected! Thanks a lot!
