### ISSUE TITLE
Localization of activity.md into Indonesian (ID)

### ISSUE THREAD

**Issue by harlyumboh** [mozilla/mozilla-club-activity-hack-the-news#5]
---

title: Hack the News
github: mozilla/mozilla-club-activity-hack-the-news
image: hackthenews.png
competencies:
### Hack Berita

Dibuat oleh [Hive New York City](http://hivenyc.org/) dan di remix untuk Klub berdasarkan [Mozilla](https://webmaker.org/mentor).

Peserta didik akan menggunakan X-Ray Goggles untuk meremix website berita, belajar tentang **sumber terbuka berlisensi, berbagai bentuk media, dan bagaimana untuk menciptakan sesuatu yang baru di Web melalui remix.**

45 menit sampai satu jam
### Persiapan

**Lengkapi** [kuesioner pra kegiatan](http://goo.gl/forms/Uua6yKIy5E).

Selanjutnya **lakukan aktifitas anda sendiri** agar menjadi familiar. Anda mungkin ingin membuat akun webmaker yang dapat Anda bagikan pada peserta didik Anda. Ini akan menghemat waktu nanti ketika mereka siap untuk mempublikasikan remix mereka

[Tinjau definisi kata "Hack"](https://wiki.mozilla.org/Webmaker/Teach/Terminology#Hack), sehingga Anda dapat membantu peserta didik ( ! dan rekan) memahami konteks positif untuk kata tersebut.

Opsional: Cetak [Contekan HTML](https://mozteach.makes.org/thimble/html-cheatsheet) dan [panduan referensi X-Ray Goggles](https://mozteach.makes.org/thimble/xray-goggles-cheatsheet).

---

10<br>menit
### Pendahuluan

Ucapkan selamat datang kepada siswa anda dan jelaskan bahwa dalam kegiatan ini kita akan mengeksplorasi "remix." Berikan setiap siswa selembar kertas dan pensil.

> dengan berpasangan, memintalah siswa anda untuk membuat sketsa karakter fiksi favorit mereka. Tidak perlu untuk akurat atau terlalu detail -. Cukup, menarik dengan cepat
> Setelah beberapa menit, buatlah mereka saling bertukar gambar dengan pasangan mereka. Ajaklah siswa untuk menambahkan sesuatu ke gambar pasangan mereka. Jelaskan bahwa ini adalah aksi remix!

---

25<br> Menit
### Hack berita menggunakan X-Ray Goggles

Masih dengan pasangan yang sama, Jika peralatan tersedia, mintalah siswa membuka penjelajah web (web browser) modern. Lainnya, setelah itu mendemonstrasikan pada satu komputer dan kelompok kecil, sehingga siswa dapat mencobanya sendiri.
#### Install X-Ray Goggles

Pergi ke [goggles.webmaker.org](https://goggles.webmaker.org/). Demonstrasikan bagaimana menggeser tombol besar kuning “Aktifkan X-Ray Goggles” ke toolbar bookmark pada browser anda.

![Gambar](http://mozilla.github.io/webmaker-curriculum/images/newshack-example-animated.gif)
#### Arahkan ke sebuah situs Berita

Mintalah saran untuk situs berita. Pikirkan tentang surat kabar lokal, koran sekolah Anda, atau situs berita nasional seperti The New York Times atau The Guardian. Cobalah untuk menemukan website yang menggunakan HTML yang baik, dan tidak banyak Javascript karena akan lebih mudah bagi peserta didik untuk me remix.

> Jangan khawatir  Anda tidak benar-benar meretes situs untuk orang lain. Anda hanya mengubah ke situs versi lokal dan hanya Anda yang dapat melihat.
#### Tentukan tema remix

Terinspirasi oleh karakter pada pendahuluan, memutuskan untuk me remix tema. Ide termasuk Nyan Cat, the Kraken, Ping Kong, atau karakter lokal serupa yang relevan. 

![gambar](http://mozilla.github.io/webmaker-curriculum/images/newshack-example.png)
#### Aktifkan Goggles

Klik Goggles pada toolbar bookmark untuk mengaktifkannya. Sekarang ketika Anda mengarahkan mouse elemen halaman berita, Anda akan melihat kode di bawahnya.
#### Tekan tombol “remix”

Tekan “R” pada keyboard untuk meremix setiap elemen.
#### Mengubah teks and gambar baru

Cobalah mengubah headline atau menulis ulang beberapa cerita berdasarkan karakter fiksi Anda. Mengedit beberapa link dan bermain dengan ukuran huruf dan warna.

Mouse over pada gambar di halaman dan tekan “R” / “Remix.” kemudian paste alamat/URL untuk gambar baru anda. Untuk mengambil gambar dari Facebook atau Instagram, Anda harus klik ke pos, kemudian klik kanan dan "Salin Lokasi gambar".

> **TIPS:** Bagaimana menemukan dan swap gambar berlisensi terbuka. Halaman pencarian atau pengaturan lanjutan Creative Commons di Google dapat membantu Anda dengan mudah menemukan gambar yang Anda sukai dengan izin untuk menggunakannya. Klik kanan atau klik kontrol pada gambar yang Anda inginkan dan pilih: "Copy Lokasi gambar " (Atau "URL Copy image" atau "Copy alamat gambar", tergantung pada browser web Anda.) Kemudian paste URL gambar baru Anda di atas dari yang lama. Hati-hati untuk tidak kehilangan tanda kutipan!

![Gambar](http://mozilla.github.io/webmaker-curriculum/images/newshack-example-2.png)
#### Berbagi

**Publikasikan remix anda.** Setelah Anda selesai, klik tombol, atau tekan P Publikasikan pada keyboard Anda. Hal ini membuat perubahan yang terlihat di web untuk orang lain untuk melihat.
**Ambil langkah lebih lanjut** Buatlah peserta didik berbagi hasil hack mereka dengan situs berita yang mereka remix. Sebagian besar stasiun berita memiliki twitter, jadi coba tweeting link ke mereka dan pikirkan tentang reaksi mereka.

---

10<br>Menit
### Refeksikan dan Tinjau

Demo beberapa halaman remix dan meminta siswa untuk berbagi apa yang mereka ubah. Pertimbangkan petunjuknya seperti:

> Apa versi website yang lebih anda sukai? Apa lagi yang akan anda remix? Apa yang ingin anda remix tetapi tidak bisa? Kenapa tidak bisa? Bagaimana lagi Anda dapat menemukan media yang dapat Anda remix?

Jika waktu memungkinkan, **Ajak siswa untuk melanjutkan dengan remixing halaman baru pasangan mereka.** Anda dapat mendiskusikan bagaimana web memudahkan untuk memodifikasi konten dengan cara ini dan bahwa kita selalu remixing dan membangun apa yang orang lain telah dibuat.

Anda juga dapat mendiskusikan kredibilitas dan bagaimana pemahaman remix mengubah cara Anda membaca atau menginterpretasikan informasi, serta berpikir tentang yang menulis itu. Hal ini dapat membangun [aktivitas Kraken sebelumnya](http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#id).

**Comment by soapdog** [comment]
Thanks a lot for your support! This is greatly appreciated! :smile_cat: 

Your translation is live at http://mozilla.github.io/mozilla-club-activity-hack-the-news/#id

yay!!!
