### ISSUE TITLE
Localization of aside.md into Indonesian (ID)

### ISSUE THREAD

**Issue by harlyumboh** [mozilla/mozilla-club-activity-hack-the-news#6]
#### Peserta
- 8+
- Berpikir Kritis pemula
#### Materials
- Ketas dan pena
- Web browser
- (opsional) [Cetakan contekan HTML](https://mozteach.makes.org/thimble/html-cheatsheet)
- (opsional) [Cetakan Petunjuk referensi X-Ray Goggles ](https://mozteach.makes.org/thimble/xray-goggles-cheatsheet)
#### Tujuan Pembelajaran
- Membedakan antara konten asli dan remix
- Menggunakan X-Ray Goggles untuk mengubah halaman web untuk memberikan tema tertentu
- Mengkritisi Hasil remix peserta didik yang lain
#### Aksi dalam Kegiatan!

![Image](http://mozilla.github.io/webmaker-curriculum/images/hackthenews-action.jpg)

[Hive Pittsburgh: Pittsburgh Project Youth Get Hacking](http://hivepgh.sproutfund.org/blog/2014/12/15/pittsburgh-project-youth-get-hacking/)
#### Lihat remix komunitas

Periksa cara pendidik dan aktivis lain yang telah dimodifikasi kegiatan ini untuk peserta mereka yang lebih spesifik di [Forum Diskusi] kami(https://discourse.webmaker.org/c/curriculum).

**Comment by soapdog** [comment]
Thanks a lot for your support! This is greatly appreciated! :smile_cat: 

Your translation is live at http://mozilla.github.io/mozilla-club-activity-hack-the-news/#id

yay!!!

**Comment by harlyumboh** [comment]
thanks so much @soapdog
