### ISSUE TITLE
Html and X-Ray goggles cheatsheet on New Thimble

### ISSUE THREAD

**Issue by alvarmaciel** [mozilla/mozilla-club-activity-hack-the-news#9]
I'm working in the localization of these kit, but the cheatsheet ar in old thimble, so I make the cheatsheet on new thimble
- [Html cheatsheet](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17418)
- [X-Ray goggles cheatsheet](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17419)

**Comment by soapdog** [comment]
Thats perfect! I will replace the links! :smile_cat: thats awesome work my friend!

**Comment by soapdog** [comment]
Fixed all the links. Thanks again for building those Alvar! :smiley_cat:
